# This a sample config file for Cairn todo list app.
#
# Cairn will look in the following folders (in this order) to find the
# cairn.conf file. The first file found will be taken into account :
# - ~/.cairn.conf
# - ~/.config/cairn.conf
# - ~/.config/cairn/cairn.conf
#
#
todofile: "~/todo.txt"
#
# Here are commands that will be executed at startup (they can also be used
# directly in the app)
:alpha 0.5
:size 600x400
:fontsize 8
:bgcolor #000000
:textcolor #FFFFFF

